# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buliding_risk_grade', models.CharField(max_length=50, verbose_name='风险等级')),
                ('buliding_risk_kind_big', models.CharField(max_length=50, verbose_name='风险大类')),
                ('buliding_risk_kind_small', models.CharField(max_length=50, verbose_name='风险小类')),
            ],
            options={
                'db_table': 'risk',
            },
        ),
    ]
