# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buliding_code', models.CharField(max_length=50, verbose_name='楼宇编码')),
                ('buliding_name', models.CharField(max_length=50, verbose_name='楼宇名称')),
                ('buliding_addr', models.CharField(max_length=50, verbose_name='小区地址/街道信息')),
                ('buliding_img', models.CharField(max_length=50, verbose_name='图片')),
                ('buliding_family_count', models.CharField(max_length=50, verbose_name='多少户')),
                ('buliding_height', models.CharField(max_length=50, verbose_name='楼的高度')),
                ('buliding_kind', models.CharField(max_length=50, verbose_name='建筑类型/住宅/商业')),
                ('buliding_type', models.CharField(max_length=50, verbose_name='建筑物结构类型1/2/3/')),
                ('buliding_create_time', models.CharField(max_length=50, verbose_name='创建时间')),
                ('buliding_create_unit', models.CharField(max_length=50, verbose_name='创建单位')),
                ('buliding_org_id', models.CharField(max_length=50, verbose_name='所属组织')),
                ('buliding_remarks', models.CharField(max_length=50, verbose_name='备注')),
            ],
            options={
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_pid', models.CharField(max_length=50, verbose_name='pid')),
                ('org_code', models.CharField(max_length=50, verbose_name='组织编码')),
                ('org_name', models.CharField(max_length=50, verbose_name='组织名称')),
                ('org_location', models.CharField(max_length=50, verbose_name='组织位置/街道信息')),
                ('org_longitude', models.CharField(max_length=50, verbose_name='经度')),
                ('org_latitude', models.CharField(max_length=50, verbose_name='纬度')),
                ('org_outline', models.CharField(max_length=50, verbose_name='轮廓')),
                ('org_leader_name', models.CharField(max_length=50, verbose_name='负责人')),
                ('org_leader_phone', models.CharField(max_length=50, verbose_name='负责人电话')),
                ('org_is_entity', models.CharField(max_length=50, verbose_name='1区域范围/2公司或部门/3小区')),
            ],
            options={
                'db_table': 'org',
            },
        ),
    ]
