# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-05 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_pid', models.CharField(max_length=50, verbose_name='pid')),
                ('power_code', models.CharField(max_length=50, verbose_name='权限编码')),
                ('power_name', models.CharField(max_length=50, verbose_name='权限名称')),
                ('power_remark', models.CharField(max_length=50, verbose_name='权限功能')),
                ('power_type', models.CharField(max_length=50, verbose_name='1菜单权限/2按钮权限（数据权限/代码实现）')),
            ],
            options={
                'db_table': 'power',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('role_pid', models.CharField(max_length=50, verbose_name='pid')),
                ('role_code', models.CharField(max_length=50, verbose_name='角色编码')),
                ('role_power_ids', models.CharField(max_length=50, verbose_name='权限id')),
                ('role_remark', models.CharField(max_length=50, verbose_name='备注/功能')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50, verbose_name='账号名')),
                ('user_role_ids', models.CharField(max_length=50, verbose_name='角色id')),
                ('user_main_role_id', models.CharField(max_length=50, verbose_name='')),
                ('user_org_ids', models.CharField(max_length=50, verbose_name='组织id')),
                ('user_org_type', models.CharField(max_length=50, verbose_name='组织类型')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('user_sex', models.CharField(max_length=50, verbose_name='用户性别')),
                ('user_password', models.CharField(max_length=50, verbose_name='密码')),
                ('user_phone', models.CharField(max_length=50, verbose_name='手机号')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
